// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlklazawmfsktdtespkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsa2xhemF3bWZza3RkdGVzcGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDcwNDMsImV4cCI6MjA2NTY4MzA0M30.iXTedlsR3UrAFA9z06crdxkOXL_046L9SG1e6Wplzl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);